site_name: Plant-it docs
site_url: https://docs.plant-it.org/
repo_url: https://github.com/MDeLuise/plant-it
repo_name: MDeLuise/plant-it
edit_uri: tree/main/online-resources/documentation/docs

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html

nav:
  - Home: 'index.md'
  - 'Server Installation': 'server-installation.md'
  - 'App Installation': 'app-installation.md'
  - 'Features': 'features.md'
  - 'Developer': 'developer.md'
  - 'Support': 'support.md'

extra:
    social:
      - icon: fontawesome/brands/github
        link: https://github.com/MDeLuise/plant-it
        name: Repository on GitHub
      - icon: fontawesome/solid/user
        link: https://massimilianodeluise.com
        name: Personal site
      - icon: simple/buymeacoffee
        link: https://buymeacoffee.com/mdeluise
        name: Buy me a coffe
    version:
      provider: mike

theme:
  name: material
  custom_dir: overrides
  logo: assets/logo.png
  favicon: assets/logo.png
  icon:
    repo: fontawesome/brands/github
  features:
    - content.action.edit
    - navigation.footer
    - navigation.path
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - toc.integrate
    - navigation.top
    - content.code.copy
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: teal
      accent: purple
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: teal
      accent: purple
